# Generated by Django 3.2.9 on 2021-11-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211115_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patterncategory',
            name='pattern',
        ),
    ]
