# Generated by Django 3.2.9 on 2021-11-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_patterncategory_pattern'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patterncategory',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='patterncategory',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='patterncategory',
            name='user',
        ),
    ]
