# Generated by Django 3.2.9 on 2021-11-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211115_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternTuturials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pattern')),
            ],
            options={
                'verbose_name': 'Pattern Tutorial',
                'verbose_name_plural': 'Pattern Tutorials',
            },
        ),
    ]
