# Generated by Django 3.2.9 on 2021-11-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_patterntuturials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterntuturials',
            name='pattern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tuturials', to='api.pattern'),
            preserve_default=False,
        ),
    ]
