# Generated by Django 3.2.9 on 2021-11-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pattern_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
