# Generated by Django 3.2.9 on 2021-11-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211115_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='pattern_categories',
            field=models.ManyToManyField(blank=True, to='api.PatternCategory'),
        ),
    ]
