# Generated by Django 3.2.9 on 2021-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pattern_pattern_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('size_abbr', models.CharField(max_length=3)),
                ('size_type', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex'), ('C', 'Child'), ('I', 'Infant'), ('O', 'Other')], max_length=1)),
            ],
            options={
                'verbose_name': 'Pattern Size',
                'verbose_name_plural': 'Pattern Sizes',
            },
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pattern_categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='api.PatternCategory'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern_sizes',
            field=models.ManyToManyField(blank=True, to='api.PatternSizes'),
        ),
    ]
